repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
#- repo: https://github.com/psf/black
#  rev: 22.10.0
#  hooks:
#    - id: black
#      args: [--line-length=80]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.9
  hooks:
    - id: ruff-format
    - id: ruff
      args: [--fix]
