version: '3.8'

services:
  pgdev:
    image: pgvector/pgvector:pg16
    container_name: postgres_db
    environment:
      POSTGRES_DB: pgvector_demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6479:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  runner:
    build: .
    container_name: runner
    environment:
      - PYTHONPATH=/app/src
      - SETTINGS_YAML=/app/settings/demo.yml
    profiles:
      - manual
    volumes:
      - ./:/app
      - /tmp/demo_pgvector/files:/files
      - tmp_workspace_data:/workspace

volumes:
  postgres_data:
  redis_data:
  tmp_workspace_data:
