# pyproject.toml
[project]
# Support Python 3.10+.
requires-python = ">=3.10"

[tool.ruff]
line-length = 80

[tool.ruff.lint]
extend-ignore = ["E501"]

[tool.ruff.format]
quote-style = 'single'
indent-style = 'space'
docstring-code-format = true
docstring-code-line-length = 80
